### ISSUE TITLE
Red 5 net error connector 

### ISSUE THREAD

**Issue by qoallen13** [Red5/red5-server#184]
[red5help.zip](https://github.com/Red5/red5-server/files/285474/red5help.zip)
# Issue

### Short description
__Brief description of what happened__

Me and my team has installed red5 server on our windows computer. We are able to see the red5 home page on our localhost:5080, but when we try to install an demo we get an net.Connection error and a missing war file error. Is there any thing we need to install seperatly or code, for the demos to work? Our server setup is XAMPP which includes apache tomcat, php, and mysql. 

Thanks for reading,

Quentin Allen
### Environment

[] Operating system and version:Windows
[] Java version:1.8.0
[] Red5 version:1.08

### Expected behavior
__Put as much detail here as possible__
We have opened the ports needed for red5 1935,5080 and the JAVA path is set. 
### Actual behavior  
__Put as much detail here as possible__

### Steps to reproduce
1. 
2. 
3. 
[log.zip](https://github.com/Red5/red5-server/files/285471/log.zip)

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

**Comment by mondain** [comment]
Resolved with issue #180

**Comment by qoallen13** [comment]
Hello I have added the code snippet that you attached into my web apps
properties. I am still seeing the net connection error page when i click
launch an demo.Is it something that i must install or program because the
error page says "missing war files"

**Comment by gocheap** [comment]
what version of windows is recommended?

**Comment by mondain** [comment]
When I use Windows, I use Windows 10 x64.
